# Generated by Django 2.2.13 on 2021-06-26 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20210314_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='item_ids',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='频率(分钟)'),
        ),
    ]
